Repository ucsb-cs156-s24/proj-happycows-s24-4pm-5, pull requests merged in 2024-05, with the labels that each got.

#34 Announcements Index Page Displaying the Correct Heading
  frontend/src/main/pages/AdminAnnouncementsPage.js
  frontend/src/tests/pages/AdminAnnouncementsPage.test.js
Labels: 5

#46 Improve Homepage UI
  frontend/src/main/components/Commons/CommonsCard.js
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/tests/components/Commons/CommonsCard.test.js
  frontend/src/tests/components/Commons/CommonsList.test.js
Labels: 10

#55 Feature: Added Create Announcement Button (Placeholder Page)
  frontend/src/App.js
  frontend/src/main/pages/AdminAnnouncementsPage.js
  frontend/src/main/pages/AdminCreateAnnouncementsPage.js
  frontend/src/tests/pages/AdminCreateAnnouncementsPage.test.js
Labels: 10, Merge Candidate

#59 Feature: Suspended field for users entity
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
Labels: Ready for Staff CR

#51 Fixed disallowing users to navigate to unjoined commons
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: Ready for Staff CR

#63 Feature: Endpoints for Suspending and Restoring Users
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UsersControllerTests.java
Labels: Ready for Staff CR
